baseurl = "/"
languageCode = "en-us"
title = "Junli Zhang's Blog"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-136755204-1"
#disqusShortname = "junli"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 1
[[menu.main]]
    name = "Blogs"
    url = "/en/"
    weight = 1
[[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 2
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 3
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/pinbo"
#    weight = 4
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/aswillow"
#    weight = 5
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
#[[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
[[menu.main]]
    name = "博客"
    url = "/cn/"
    weight = 7
[[menu.main]]
    name = "Contact Me"
    url = "/contact_me/"
    weight = 8

[params]
    description = "A website to share knowledge and ideas."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "home.svg"
    width = 60
    height = 60
    alt = "Logo"

